export const LeaguesDict = {
    'UEFA Champions League': '🇪🇺 Лига Чемпионов УЕФА 🔥',
    Bundesliga: '🇩🇪 Бундеслига',
    'Premier League': '🏴󠁧󠁢󠁥󠁮󠁧󠁿 Английская Премьер Лига',
    'Primera Division': '🇪🇸 Ла Лига',
    'Serie A': '🇮🇹 Сериа А',
    'Ligue 1': '🇫🇷 Лига 1',
};

export const standingsDict = {
    Rank: 'Место',
    Squad: 'Команда',
    'Matches Played': '🆚 Матчей сыграно',
    Wins: '🏆 Победы',
    Draws: '🤝 Ничьи',
    Losses: '🚫 Поражения',
    'Goals For': '⚽️ Забитые голы',
    'Goals Against': '❌ Пропущенные голы',
    'Goal Difference': '♻️ Разница мячей',
    Points: '✅ Очки',
    'Points/Game': '♻️ Очки/Матчи',
    xG: '🔺 Ожидаемые голы (xG)',
    'xG Allowed': '🔻 Допущенные xG',
    'xG Difference': '📊 Разница xG',
    'xG Difference/90': '♻️ Разница xG/Матч',
    'Last 5': '📊 Последние 5 матчей',
    'Attendance/Game': '📈 Средняя посещаемость стадиона',
    'Top Team Scorer': '⚽️ Лучший бомбардир',
    Goalkeeper: 'Вратарь',
    Notes: '',
};